[package]
name = "echo"
version = "1.0.0"
edition = "2021"
author = "Subwoofy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.17", features = ["derive"] }
thiserror = "1.0.56"
color-eyre = "0.6.2"
